# Keras Basics

The notebook belongs to the first part of the section, which focuses on basic Deep Learning concepts. I have notes on these concepts already in previous documents:

- `~/Dropbox/Documentation/howtos/keras_tensorflow_guide.txt`
- `~/git_repositories/data_science_python_tools/19_NeuralNetworks_Keras`

The latter is a section in the repository [data_science_python_tools](https://github.com/mxagar/data_science_python_tools). It contains specific topics relevant to NLP:

- Keras basics
- RNNs
- NLP

In the following, the classification problem of the [Iris dataset](https://archive.ics.uci.edu/ml/datasets/iris) is solved using Keras. The notebook is quite uninteresting, unless you'd like to know how to perform a vanilla classification with tabular data using Keras.

Overview of contents:
1. Load & Prepare the Dataset
    - 1.1 Get the Dataset
    - 1.2 Train/Test Split
    - 1.3 Scale
2. Model Definition and Training
3. Evaluation & Inference
4. Save and Load Models

*Diclaimer: I made this notebook while following the Udemy course [NLP - Natural Language Processing with Python](https://www.udemy.com/course/nlp-natural-language-processing-with-python/) by José Marcial Portilla. The original course notebooks and materials were provided with a download link, I haven't found a repository to fork from.*

## 1. Load & Prepare the Dataset

### 1.1 Get the Dataset

In [1]:
import numpy as np

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
X = iris.data

In [6]:
X.shape

(150, 4)

In [7]:
y = iris.target

In [8]:
y.shape

(150,)

In [9]:
# One-Hot Encoding
from keras.utils import to_categorical

Using TensorFlow backend.


In [10]:
y = to_categorical(y)

In [19]:
y.shape

(150, 3)

### 1.2 Train/Test Split

In [12]:
from sklearn.model_selection import train_test_split

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

### 1.3 Scale

In [14]:
from sklearn.preprocessing import MinMaxScaler

In [15]:
scaler_object = MinMaxScaler()

In [16]:
scaler_object.fit(X_train)

MinMaxScaler()

In [17]:
scaled_X_train = scaler_object.transform(X_train)

In [18]:
scaled_X_test = scaler_object.transform(X_test)

## 2. Model Definition and Training

In [21]:
from keras.models import Sequential
from keras.layers import Dense

In [22]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(8, input_dim=4, activation='relu'))
model.add(Dense(3, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

2022-04-25 14:38:04.360308: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-25 14:38:04.362093: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 8. Tune using inter_op_parallelism_threads for best performance.


In [23]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_2 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 27        
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [26]:
# Play around with number of epochs as well
model.fit(scaled_X_train,y_train,epochs=150, verbose=1)

Epoch 1/150
100/100 [==============================] - 0s 321us/step - loss: 0.2077 - accuracy: 0.9500
Epoch 2/150
100/100 [==============================] - 0s 123us/step - loss: 0.2061 - accuracy: 0.9500
Epoch 3/150
100/100 [==============================] - 0s 109us/step - loss: 0.2045 - accuracy: 0.9600
Epoch 4/150
100/100 [==============================] - 0s 80us/step - loss: 0.2041 - accuracy: 0.9500
Epoch 5/150
100/100 [==============================] - 0s 72us/step - loss: 0.2057 - accuracy: 0.9400
Epoch 6/150
100/100 [==============================] - 0s 86us/step - loss: 0.2083 - accuracy: 0.9300
Epoch 7/150
100/100 [==============================] - 0s 68us/step - loss: 0.2069 - accuracy: 0.9300
Epoch 8/150
100/100 [==============================] - 0s 73us/step - loss: 0.2044 - accuracy: 0.9300
Epoch 9/150
100/100 [==============================] - 0s 60us/step - loss: 0.2030 - accuracy: 0.9300
Epoch 10/150
100/100 [==============================] - 0s 77us/step - loss: 0.

## 3. Evaluation & Inference

In [29]:
# Classes
model.predict_classes(scaled_X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 2, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [30]:
# Probabilities
model.predict(scaled_X_test)

array([[3.7953616e-03, 9.0139675e-01, 9.4807856e-02],
       [9.9653494e-01, 3.4641160e-03, 9.1317844e-07],
       [7.3805516e-08, 1.4495703e-03, 9.9855036e-01],
       [2.1918260e-03, 7.8061134e-01, 2.1719687e-01],
       [1.0858449e-03, 6.9031870e-01, 3.0859539e-01],
       [9.9122107e-01, 8.7745525e-03, 4.3619834e-06],
       [8.6726956e-03, 9.6232158e-01, 2.9005803e-02],
       [6.6943517e-06, 2.9191446e-02, 9.7080189e-01],
       [7.5135677e-04, 3.6511612e-01, 6.3413250e-01],
       [7.1674120e-03, 9.5278430e-01, 4.0048312e-02],
       [1.0109660e-04, 1.7444783e-01, 8.2545114e-01],
       [9.9169993e-01, 8.2937656e-03, 6.3960774e-06],
       [9.9648488e-01, 3.5139995e-03, 1.0654983e-06],
       [9.9307936e-01, 6.9160634e-03, 4.6540308e-06],
       [9.9727708e-01, 2.7222310e-03, 7.6336289e-07],
       [1.4529370e-03, 7.9644883e-01, 2.0209828e-01],
       [4.7645490e-06, 1.7412972e-02, 9.8258221e-01],
       [9.9841664e-03, 9.5068008e-01, 3.9335787e-02],
       [4.6059252e-03, 8.939

In [31]:
model.metrics_names

['loss', 'accuracy']

In [32]:
model.evaluate(x=scaled_X_test,y=y_test)

50/50 [==============================] - 0s 2ms/step


[0.10343486696481705, 0.9599999785423279]

In [33]:
from sklearn.metrics import confusion_matrix,classification_report

In [34]:
predictions = model.predict_classes(scaled_X_test)

In [35]:
confusion_matrix(y_test.argmax(axis=1),predictions)

array([[19,  0,  0],
       [ 0, 14,  1],
       [ 0,  1, 15]])

In [36]:
print(classification_report(y_test.argmax(axis=1),predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



## 4. Save and Load Models

In [37]:
model.save('myfirstmodel.h5')

In [38]:
from keras.models import load_model

In [39]:
newmodel = load_model('myfirstmodel.h5')

In [40]:
newmodel.predict_classes(X_test)

array([2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 1, 2,
       1, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1,
       1, 2, 2, 2, 2, 2])